const paragraphs = [
  "Once upon a time in the fantastical land of Whimsytopia, where marshmallow clouds rained confetti and bubblegum trees whispered jokes, a peculiar event unfolded. The renowned Snicker Snail Marathon was about to begin, featuring snails with turbocharged giggles propelling them forward. Spectators gathered, armed with feather dusters to tickle the snails if they slowed down. The winner received a lifetime supply of helium balloons, causing a helium shortage across the land and leading to the hilarious predicament of floating houses and talking squirrels with squeaky voices.",

  "Deep in the heart of Jovial Junction, where the aroma of chocolate chip cookies wafted through the air, an extraordinary baking competition took place. The participants, dressed as singing cupcakes and tap-dancing muffins, concocted desserts infused with laughter. The highlight was a cake that told knock-knock jokes as it was sliced, leaving everyone in stitches. The uproarious event ended with a confetti explosion, covering the entire town in a colorful shower of joy.",

  "In the whimsical city of Chuckleville, where clowns moonwalked and rubber chickens hosted talk shows, an ambitious group of rubber ducks embarked on a mission. They aimed to create the world's largest rubber duck pyramid. The endeavor led to a series of comical mishaps, with ducks quacking in harmony and performing synchronized flips. The grand finale involved the ducks forming a giant smiley face visible from space, spreading laughter across the globe.",

  "In the mythical realm of Giggletopia, where rainbow-hued elephants painted the sky and flying kittens delivered mail, an extraordinary sports event unfolded. The Laughing Olympics featured events like synchronized chuckling, belly-laugh marathons, and synchronized snorkel-snorting competitions. The victorious athletes, adorned with glittering jesters' hats, celebrated with a parade of dancing unicorns and a spectacular fireworks display of exploding joy bubbles.",

  "On the eccentric island of Chuckleberry, where jellybean rivers flowed and talking cacti told puns, an unconventional transportation system was implemented. Giant bouncing mushrooms, affectionately called 'Boing Shrooms,' became the primary mode of travel. Commuters hopped aboard the whimsical fungi, bouncing through the landscape with gleeful abandon. The island's residents soon mastered the art of mid-air somersaults, turning their daily commutes into a gravity-defying circus.",

  "In the town of Mirthville, where marshmallow pillows were the currency and tickle fights determined leadership, an outlandish talent show captivated the community. Performers showcased bizarre skills, including interpretative dancing avocados, opera-singing rubber bands, and breakdancing penguins. The uproarious applause caused a popcorn explosion, covering the entire venue in a confetti of popcorn kernels. The town unanimously declared it the most entertaining mishap ever.",

  "Within the peculiar village of Quibbleburg, where rubber chickens held political debates and dancing shadows had their own fan club, an uproarious discovery was made. The citizens stumbled upon a portal to a dimension where all knock-knock jokes came to life. The town was soon populated with living punchlines, creating a surreal atmosphere of perpetual laughter. Residents delighted in conversations with literal jokesters, transforming their daily interactions into a sidesplitting comedy routine.",

  "On the cosmic playground of Chuckletron-9, where shooting stars told dad jokes and moonwalking aliens taught dance classes, a peculiar space mission unfolded. Astronauts, equipped with giggle-inducing space suits, embarked on a quest to discover the source of intergalactic laughter. Their journey led them to a planet made entirely of jellybeans, where the inhabitants communicated through synchronized chuckles. The astronauts returned home with the cosmic secret to eternal joy.",

  "In the laugh-filled kingdom of Chucklington, where clouds formed into smiley faces and every day was 'Bring Your Pet Banana to Work' day, a peculiar contest took place. The 'Silent Chuckle Challenge' invited participants to convey laughter without making a sound. The finalists included a mime using invisible laughter bubbles and a ninja whose silent chuckles created ripples of joy. The winner received a trophy shaped like a whimsical snicker-snail, inspiring laughter for generations to come.",

  "Within the whimsically enchanted forest of Chucklewood, where trees hummed cheerful tunes and mischievous fairies replaced leaves with feather pens, a grand event unfolded. The Annual Giggling Tree Contest celebrated trees with the most infectious laughter. The winning tree, affectionately named 'Sir Chuckletrunk,' showered the forest with a cascade of joyful leaves, turning the entire woodland into a symphony of laughter and whimsy.",
];
